author:
  name: Björn
title: Tips and Tricks to Remember
description: >-
  An ever growing collection of very nice, but too easily forgettable tricks,
  collected by me
baseurl: ""
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/bjoernahrens" }
    - { platform: mastodon, user_url: "https://mastodon.social/@b3arco" }
    - { platform: twitter, user_url: "https://twitter.com/b3arco" }

twitter_username: B3ARco
github_username: bjoernahrens

theme: minima
plugins:
  - jekyll-feed

collections:
  - setup-guide
  - Accessibility
  - Apple_Development
  - Dotfiles
  - Flutter
  - git
  - gpg
  - Homebrew
  - iOS-apps
  - Jekyll
  - macOS
  - macOS-apps
  - macOS-quicklook
  - markdown
  - Maven
  - Python
  - SQL
  - SSH
  - Terminal_Tools
  - watchOS
  - Web_Development
  - fish
  - zsh
  - Random
